
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xhfaakeffedbudjhvhvf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhoZmFha2VmZmVkYnVkamh2aHZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1NzMzNzMsImV4cCI6MjA2MDE0OTM3M30.92GOyYN7OySPGTmrTrFJz8SWG1sWRMr_Npi9BeYH9LU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
